language: elixir
sudo: false
otp_release:
  - 20.2.2
elixir:
  - 1.6
services:
  - postgresql
addons:
  postgresql: "9.6"
cache:
  directories:
    - _build
    - deps
script:
  - MIX_ENV=test mix test
  # You need to compile following the line at first in the development environment (MIX_ENV=dev)
  - mix compile --warnings-as-errors
  - mix format --check-formatted
  - mix credo --strict
  # https://github.com/jeremyjh/dialyxir#command-line-options
  # > exit immediately with same exit status as dialyzer. useful for CI
  - mix dialyzer --halt-exit-status
deploy:
  provider: heroku
  api_key:
    # travis encrypt $(heroku auth:token) --add deploy.api_key
    secure: Hpki82sDWcB6wWl9LqLplwOgHxoSMA3XnhBYkF7oB3YE9xBOzEU+1d5Dncnid8g3hy+TPJutWtkg59Ivx5Raw3LkZQOJl0kIcC4JBfgS26oFDLcZdxX/+ampSnzq1c8NXt7lUfJ/G1tTrFJ4wU0uPhbCG+V94glVtw5dLp3/MZjrcn0FhFkeiPr34T2hh6A1Z/RVfcAA6qQL6+8zXMH1u2ewndCMKj8TVilG2lTr7KYPHV+3IsDNej8JeUQ+EdjKbMjlI+url2zC7cRba8e+mIRVQQ+QzTR4xAVZviAcfhxDO25D3q6Qw985Sulx6Xa72s/e/FnZKAYsGGk/ukBsN3L1q82AyWkqDVH81oF452lg+3VxP31YBlBkKMgdRJ2VYNhHUhPlJotO0Sjkno7yz8fFEbfbt5/6rAq0bbGNOnsTvhpAVj/b6QrwOzsHPL48dHg8APqhp/2LxYUO6/ofpfHQCrbIMgsk0q3JGW7PxIkZn4zKTOlnfRdJ2C3/SBDzMvLwLYNcscisu2iu+/jIDHjeizOMAur3e31XQCwJknlDOsloJwtukltXn3tuB6TcvkZugP2VUct8dnb4qkO7w4hUZBp1Mpj1kkm7rqZ5qgTlWe1hw/qmex9ukW5zWFD/nMA3XNbyFoL89+LnQu+VFCd20ekGrUWlYujN/cTU+fU=
  on: master
